export const FETCH_REQUEST = "FETCH_REQUEST" 
export const FETCH_SUCCESS = "FETCH_SUCCESS" 
export const FETCH_FILTERED = "FETCH_FILTERED" 
export const FETCH_SEARCH = "FETCH_SEARCH" 
export const FETCH_DETAILS = "FETCH_DETAILS" 
export const FETCH_ERROR_All = "FETCH_ERROR_All" 
export const FETCH_ERROR_Details = "FETCH_ERROR_Details" 